// SPIKE-012 §2 step 4: the pivotal move. A small, fixed set of multiple-choice questions —
// never free construction — decide the exact modeling questions today's single global
// vocabulary call gets wrong or overreaches on (SPIKE-011 §4/§5.7): is a group the ENTITY AXIS
// (things clues refer to individually — houses, suspects) or a set of DOMAIN VALUES some axis
// takes (colors, weapons)? Does an axis have an implied spatial/temporal ordering, and if so —
// scoped to WHICH axis, never a single bare "position" — does it need a synthesized positional
// domain? These are exactly the decisions SPIKE-011's fix 1 made unprompted and unscoped (working
// on PZL-0001, overreaching on PZL-0004); here they're explicit, closed choices, and the
// synthesized domain's name is generated by CODE, always scoped to its own entity axis, so the
// SAME collision class fix 1 introduced cannot recur by construction.

import { requestClueTool } from "../../../SPIKE-008-per-clue-tool-call-decomposition/scripts/lib/tool-call.ts"
import type { CanonicalGroup } from "./group.ts"
import type { Entity, Domain } from "../../../../../src/extraction/types.ts"

const SHAPE_SCHEMA = {
  type: "object",
  properties: {
    classifications: {
      type: "array",
      items: {
        type: "object",
        properties: {
          group_index: { type: "integer" },
          role: {
            type: "string",
            enum: ["entityAxis", "domainValues"],
            description: '"entityAxis": this group\'s members are individual things clues refer to by identity (e.g. houses, suspects, days). "domainValues": this group is a set of interchangeable attribute values some entity axis takes (e.g. colors, weapons, drinks) — never referenced individually by clues, only assigned.',
          },
          entity_axis_group_index: {
            anyOf: [{ type: "integer" }, { type: "null" }],
            description: "Only meaningful when role is \"domainValues\": the group_index of the entityAxis group whose members take these values. Null for entityAxis groups, or if this domainValues group doesn't clearly range over any one declared axis (e.g. a puzzle with no distinct \"rows\" at all).",
          },
        },
        required: ["group_index", "role", "entity_axis_group_index"],
        additionalProperties: false,
      },
    },
    entity_axes_needing_synthesized_ordering: {
      type: "array",
      items: { type: "integer" },
      description: 'group_index of every entityAxis group where the puzzle establishes a spatial or temporal ORDER among that axis\'s members (e.g. "five houses in a row, left to right", "three appointments in sequence") that is NOT already one of the domainValues groups above. Leave empty if no such implicit ordering exists — do not include an axis just because it has multiple members.',
    },
  },
  required: ["classifications", "entity_axes_needing_synthesized_ordering"],
  additionalProperties: false,
} as const

function systemPrompt(groups: readonly CanonicalGroup[]): string {
  const listed = groups.map((g, i) => `${i}: "${g.label}" (${g.members.length} member${g.members.length === 1 ? "" : "s"}: ${g.members.map((m) => m.text).join(", ")})`).join("\n")
  return (
    "You are deciding the STRUCTURE of a constraint-satisfaction puzzle from its already-grouped " +
    "categories. For each group, decide whether it is the ENTITY AXIS (individual things — " +
    'houses, suspects, days — that clues refer to by identity and that get assigned values) or a ' +
    "set of DOMAIN VALUES (colors, weapons, drinks — interchangeable values some entity axis " +
    "takes, never referenced individually).\n\n" +
    "IMPORTANT: not every puzzle has a real entity axis. A puzzle that is narrowing down a " +
    'SINGLE unnamed scenario (e.g. "there has been a murder — who did it, with what, where?") ' +
    "has NO entity axis at all — every group (suspect, weapon, room, ...) is DOMAIN VALUES, none " +
    "is an entity axis, and each domain's entity_axis_group_index should be null. Do NOT default " +
    "every group to entityAxis just because its members could theoretically be referred to by " +
    "name — ask instead: does this puzzle have MULTIPLE distinct things (rows) each independently " +
    "taking one value per category, or is it narrowing down ONE unstated thing across several " +
    "categories at once? Only the former needs an entity axis. It is entirely normal, and " +
    "correct, for every single group in a puzzle to be classified domainValues with a null axis.\n\n" +
    "Then flag which entity axes have an implied ordering " +
    "the puzzle states but no group already represents as explicit position labels.\n\n" +
    `Groups:\n${listed}`
  )
}

export interface ShapeResult {
  readonly entities: readonly Entity[]
  readonly domains: readonly Domain[]
  /** groupIndex -> the entity id assigned to each of its members, for entityAxis groups; and for
   * domainValues groups, groupIndex -> the domain `variable` name, so later stages can look up
   * "which domain does canonical group N become" without re-deriving it. */
  readonly domainVariableByGroupIndex: ReadonlyMap<number, string>
  readonly entityAxisTypeByGroupIndex: ReadonlyMap<number, string>
  readonly costUsd: number | undefined
  readonly calls: number
}

const SCENARIO_ENTITY_TYPE = "scenario"
const SCENARIO_ENTITY_ID = "the_scenario"

/**
 * Turns the model's small, closed classification answers into `entities`/`domains` — entirely
 * deterministic, no further LLM involvement. A `domainValues` group with no valid entity-axis
 * reference (null, out of range, or pointing at a group that wasn't itself classified
 * `entityAxis`) falls back to ONE shared synthesized singleton entity (`the_scenario`) — the
 * same shape the real pipeline's own successful extractions already use for a scalar,
 * single-implicit-subject puzzle (e.g. PZL-0004's "Murder" entity), rather than leaving the
 * domain homeless.
 */
export function buildVocabulary(
  groups: readonly CanonicalGroup[],
  classifications: readonly { group_index: number; role: "entityAxis" | "domainValues"; entity_axis_group_index: number | null }[],
  orderingAxisIndices: readonly number[],
): { readonly entities: Entity[]; readonly domains: Domain[]; readonly domainVariableByGroupIndex: Map<number, string>; readonly entityAxisTypeByGroupIndex: Map<number, string> } {
  const byIndex = new Map(classifications.map((c) => [c.group_index, c]))
  const entities: Entity[] = []
  const domains: Domain[] = []
  const entityAxisTypeByGroupIndex = new Map<number, string>()
  const domainVariableByGroupIndex = new Map<number, string>()
  let scenarioEntityUsed = false

  // Pass 1: entity axes first, so domainValues can resolve their entity_axis_group_index against
  // an already-known type id.
  groups.forEach((g, groupIndex) => {
    const c = byIndex.get(groupIndex)
    if (c?.role !== "entityAxis") return
    entityAxisTypeByGroupIndex.set(groupIndex, g.typeId)
    for (const m of g.members) entities.push({ id: m.id, type: g.typeId })
  })

  // Pass 2: domain values, resolving each against a known entity axis or the shared scenario
  // fallback.
  groups.forEach((g, groupIndex) => {
    const c = byIndex.get(groupIndex)
    if (c?.role !== "domainValues") return
    const axisType =
      c.entity_axis_group_index !== null ? entityAxisTypeByGroupIndex.get(c.entity_axis_group_index) : undefined
    const entityType = axisType ?? SCENARIO_ENTITY_TYPE
    if (axisType === undefined && !scenarioEntityUsed) {
      entities.push({ id: SCENARIO_ENTITY_ID, type: SCENARIO_ENTITY_TYPE })
      scenarioEntityUsed = true
    }
    domains.push({ variable: g.typeId, entityType, values: g.members.map((m) => m.text) })
    domainVariableByGroupIndex.set(groupIndex, g.typeId)
  })

  // Pass 3: synthesize a positional domain for every flagged entity axis, named
  // `${axisType}_position` — always scoped to its own axis, never a single bare "position",
  // which is the exact fix for the SPIKE-011 §4/§5.7-observed PZL-0004 regression (three
  // identically-named "position" domains colliding across unrelated entity types).
  for (const axisGroupIndex of orderingAxisIndices) {
    const axisType = entityAxisTypeByGroupIndex.get(axisGroupIndex)
    if (axisType === undefined) continue // flagged an index that wasn't actually an entityAxis — ignore rather than crash
    const memberCount = groups[axisGroupIndex]?.members.length ?? 0
    if (memberCount === 0) continue
    domains.push({
      variable: `${axisType}_position`,
      entityType: axisType,
      values: Array.from({ length: memberCount }, (_, i) => String(i + 1)),
    })
  }

  return { entities, domains, domainVariableByGroupIndex, entityAxisTypeByGroupIndex }
}

type ShapeClassification = { group_index: number; role: "entityAxis" | "domainValues"; entity_axis_group_index: number | null }

async function requestClassification(model: string, groups: readonly CanonicalGroup[], extraHint: string): Promise<{ readonly classifications: readonly ShapeClassification[]; readonly orderingAxes: readonly number[]; readonly costUsd: number | undefined; readonly ok: boolean }> {
  const result = await requestClueTool({
    model,
    systemPrompt: systemPrompt(groups),
    userPrompt: `Classify every group above and flag any entity axes needing a synthesized ordering.${extraHint}`,
    schemaName: "classify_shape",
    jsonSchema: SHAPE_SCHEMA,
  })
  if (!result.ok) return { classifications: [], orderingAxes: [], costUsd: result.costUsd, ok: false }
  const value = result.value as { classifications: readonly ShapeClassification[]; entity_axes_needing_synthesized_ordering: readonly number[] }
  return { classifications: value.classifications, orderingAxes: value.entity_axes_needing_synthesized_ordering, costUsd: result.costUsd, ok: true }
}

/**
 * Found live (2026-09-15, PZL-0004 dry-run): a model can classify EVERY group `entityAxis`,
 * leaving zero domains — which cascades into `clue-schema.ts`'s zero-domain fallback (an
 * UNSCOPED free-string schema, the one edge case that fallback's own comment documents as "this
 * shouldn't happen" for a single global vocabulary call, but does happen here when shape
 * misjudges a no-entity-axis puzzle like Whodunit). One retry, with the specific nudge that
 * every-group-is-domainValues is a legitimate answer, catches the common case; a second
 * zero-domain result is returned as-is (logged as `degenerate`) rather than looping indefinitely.
 */
export async function extractShape(model: string, groups: readonly CanonicalGroup[]): Promise<ShapeResult & { readonly degenerate: boolean }> {
  let totalCost = 0
  let anyCost = false
  const addCost = (c: number | undefined) => {
    if (c !== undefined) {
      totalCost += c
      anyCost = true
    }
  }

  const first = await requestClassification(model, groups, "")
  addCost(first.costUsd)
  let calls = 1
  if (!first.ok) {
    return { entities: [], domains: [], domainVariableByGroupIndex: new Map(), entityAxisTypeByGroupIndex: new Map(), costUsd: anyCost ? totalCost : undefined, calls, degenerate: true }
  }
  let built = buildVocabulary(groups, first.classifications, first.orderingAxes)

  if (built.domains.length === 0 && groups.length > 0) {
    const hint =
      "\n\nYour previous answer classified EVERY group as entityAxis, leaving no domainValues at " +
      "all — that means nothing has a value to assign. If this puzzle is narrowing down one " +
      "unstated scenario (no real entity axis at all), reclassify every group as domainValues " +
      "with a null entity_axis_group_index instead."
    const retry = await requestClassification(model, groups, hint)
    addCost(retry.costUsd)
    calls += 1
    if (retry.ok) {
      const retryBuilt = buildVocabulary(groups, retry.classifications, retry.orderingAxes)
      if (retryBuilt.domains.length > 0) built = retryBuilt
    }
  }

  return { ...built, costUsd: anyCost ? totalCost : undefined, calls, degenerate: built.domains.length === 0 && groups.length > 0 }
}
